{% set name = "per4m" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ad88154af2e6b2c0d2234f14de1f3542e9f2fc454adcbf005bbd1fe395eaae6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - per4m = per4m.__main__:main
    - giltracer = per4m.giltracer:main
    - perf-pyrecord = per4m.record:main
    - perf-pyscript = per4m.script:main
    - offgil = per4m.offgil:main
  # https://github.com/maartenbreddels/per4m/issues/10
  skip: true  # [py>=311]

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pip
    - pybind11
  run:
    - python
    - tabulate

test:
  imports:
    - per4m
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  summary: Profiling and tracing information for Python using viztracer and perf, the GIL exposed.
  home: https://github.com/maartenbreddels/per4m
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
