schema_version: 1

context:
  name: per4m
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 1ad88154af2e6b2c0d2234f14de1f3542e9f2fc454adcbf005bbd1fe395eaae6
  patches:
    - importlib-metadata.patch

build:
  number: 4
  # https://github.com/maartenbreddels/per4m/issues/10
  skip:
    - match(python, ">=3.11")
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - per4m = per4m.__main__:main
      - giltracer = per4m.giltracer:main
      - perf-pyrecord = per4m.record:main
      - perf-pyscript = per4m.script:main
      - offgil = per4m.offgil:main

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - pip
        - pybind11
        - python
        - setuptools
        - setuptools-scm
        - wheel
  host:
    - pip
    - pybind11
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - numpy
    - python
    - tabulate
    - viztracer <0.16

tests:
  - python:
      imports:
        - per4m
  - script:
      - pip check
      - python run_test.py
      - per4m --help
      - per4m perf2trace --help
      - perf-pyrecord --help
      - perf-pyscript --help
      - offgil --help
    files:
      recipe:
        - run_test.py
    requirements:
      run:
        - pip
        - python

about:
  homepage: https://github.com/maartenbreddels/per4m
  repository: https://github.com/maartenbreddels/per4m
  summary: Profiling and tracing information for Python using viztracer and perf, the GIL exposed.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
